version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: fly-distance-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airports
    ports:
      - "5435:5436"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fly-distance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  fly-distance-network:
    driver: bridge

volumes:
  postgres-data: 